Using-vc-respec
w3c/vc-overview pull request #11
Opened 2024-06-25 13:26 UTC by iherman

The relevant examples (on JOSE/COSE and ecdsa/eddsa) us now vc-respec to display the secured credentials. I have also added an example in the appendix that includes all respec-vc possibilities in one place.

Note that these do not cover all; afaik, the jcs alternatives for ecdsa and eddsa are not covered by respec-vc. But that is all right.

2024-06-25 16:46 UTC, decentralgabe approved these changes

2024-07-01 18:56 UTC, TallTed requested changes
Editorial, grammar, etc.

2024-07-01 18:56 UTC, TallTed commented on index.html
> +          These are encoded, concatenated, and signed, to be transferred in a compact form by one entity to an other
```suggestion
          These are encoded, concatenated, and signed, to be transferred in a compact form by one entity to another 
```

2024-07-01 18:56 UTC, TallTed commented on index.html
> +          <h4>Example: the Core Example Secured with ECDSA adn EdDSA</h4>
```suggestion
          <h4>Example: the Core Example Secured with ECDSA and EdDSA</h4>
```

2024-07-01 18:56 UTC, TallTed commented on index.html
> +        <a href="#base_example_status_list"></a> shows our example from <a href="#base_example_secured_di"></a>, combined with the information on the credential status: the purpose of that status inf
```suggestion
        <a href="#base_example_status_list"></a> shows the example from <a href="#base_example_secured_di"></a>, combined with the information on the credential status: the purpose of that status information, the reference to the bitstring, and the index into this bitstring for the enclosing credential: 
```

2024-07-01 18:56 UTC, TallTed commented on index.html
> +        <a href="#complete_example"></a> shows our Credential example used throughout this document, enriched with a
```suggestion
        <a href="#complete_example"></a> shows the Credential example used throughout this document, enriched with a 
```

2024-07-02 18:01 UTC, TallTed approved these changes

2024-07-03 01:08 UTC, davidlehn commented on index.html
> +         postProcess: [
```suggestion
        postProcess: [
```

2024-07-03 04:01 UTC, merged