Updated the cryptosuite sections, mostly the Selective Disclosure part
w3c/vc-overview pull request #16
Opened 2024-10-14 13:56 UTC by iherman

Hopefully I got it right now...

2024-10-14 19:20 UTC, dlongley commented on index.html
> +              encoded to provide as a Multikey formatted `proofValue`.
```suggestion
              encoded to provide as a multibase-formatted `proofValue`. 
```

2024-10-15 04:37 UTC, iherman commented on index.html
> +              encoded to provide as a Multikey formatted `proofValue`.
Oops...

2024-10-16 16:23 UTC, Wind4Greg requested changes
Hi Ivan, looks pretty good but a couple things are confusing to read or not quite accurate. (1) You use the term "[general data integrity structure](https://pr-preview.s3.amazonaws.com/w3c/vc-overview/pull/16.html#di-integrity-structure) when it seems that this is a "procedure" that produces a "structure". (2) The use of a "challenge" is not specific to SD schemes, and in fact BBS would use a different approach to achieving the same thing.

2024-10-17 13:01 UTC, iherman commented
Thank you @Wind4Greg 

> (1) You use the term "[general data integrity structure](https://pr-preview.s3.amazonaws.com/w3c/vc-overview/pull/16.html#di-integrity-structure) when it seems that this is a "procedure" that produces a "structure". 

Right. This was the result of a poor choice for the title of section 4.2.1.; I have changed that and made the changes in the references. I hope it is better now.

> (2) The use of a "challenge" is not specific to SD schemes, and in fact BBS would use a different approach to achieving the same thing.

I removed the term and reformulated/removed the sentences that used it.

I hope it is better now!

2024-10-22 15:22 UTC, merged

2024-10-23 06:22 UTC, iherman commented on index.html
> +          <img style="margin: auto; display: block; width: 100%;" src="diagrams/VCWG_specifications.svg" alt="Diagram illustrating the structure of the Verifiable Credentials (VCs) specification, usi
See https://github.com/w3c/vc-overview/pull/17. The PR was closed by the time you made this comment...