Minor fix
w3c/vc-overview pull request #4
Opened 2024-05-16 15:05 UTC by mkhraisha

2024-05-16 15:52 UTC, iherman approved these changes

2024-05-16 18:23 UTC, TallTed requested changes
Small language improvements

2024-05-16 18:23 UTC, TallTed commented on index.html
> +          When Verifiable Credentials are serialized in JSON, it is important to trust that the structure of a Credential may be interpreted in a consistent manner by all participants of the verifiab
```suggestion
          When Verifiable Credentials are serialized in JSON, it is important to trust that the structure of a Credential may be interpreted in a consistent manner by all participants in the verifiable credential ecosystem.
```

2024-05-16 18:23 UTC, TallTed commented on index.html
> +          In the enveloping case the proof wraps around the Credential, whereas embedded proofs are included in the serialization, alongside the Credential itself.
```suggestion
          In the enveloping case, the proof wraps around the Credential, whereas embedded proofs are included in the serialization, alongside the Credential itself.
```

2024-05-16 18:23 UTC, TallTed commented on index.html
> +            The exact format, when used for Credentials, of the public keys is defined in the [[CONTROLLER-DOCUMENT]] specification, and is based on either the JWK [[RFC7517]] format or a Multibase [
```suggestion
            The exact format of the public keys, when used for Credentials, is defined in the [[CONTROLLER-DOCUMENT]] specification, and is based on either the JWK [[RFC7517]] format or a Multibase [[MULTIBASE]] encoding of the keys, called <a data-cite="VC-DATA-INTEGRITY#multikey">Multikey</a>.
```

2024-05-16 18:23 UTC, TallTed commented on index.html
> +            When dereferenced, the URL `did:example:2g55q912ec3476eba2l9812ecbfe#ecdsa-public-key` should return a ECDSA public key in Multikey format, for example:
```suggestion
            When dereferenced, the URL `did:example:2g55q912ec3476eba2l9812ecbfe#ecdsa-public-key` should return an ECDSA public key in Multikey format, for example:
```

2024-05-16 18:23 UTC, TallTed commented on index.html
> +          The verifier validates claims made in the verifiable credential against their business rules.
```suggestion
          The verifier validates claims made in the verifiable credential against the verifier's business rules.
```

2024-05-22 12:35 UTC, iherman commented
Comments have been adopted, not controversial, merging.

2024-05-22 12:35 UTC, merged